pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('a930af01-7285-420d-b3b5-66a9b5dd7752')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {
        stage('Clone github repository') {
            steps {
                cleanWs() // Очищаем рабочую директорию
                sh '''
                    git clone -b main https://github.com/Alex-Andrv/mle-lab4.git
                '''
            }
        }

        stage('Checkout repo dir') {
            steps {
                sh '''
                    cd mle-lab4
                    ls -la
                '''
            }
        }

        stage('Login') {
            steps {
                sh 'export PATH=$PATH:/usr/local/bin && /usr/local/bin/docker --version'
                sh 'echo $DOCKERHUB_CREDS_USR'
                sh '''
                    echo $DOCKERHUB_CREDS_PSW | /usr/local/bin/docker login -u $DOCKERHUB_CREDS_USR --password-stdin
                '''
            }
        }

        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        sh '''
                            cd mle-lab4
                            export PATH=$PATH:/usr/local/bin && /usr/local/bin/docker-compose build
                        '''
                    } finally {
                        sh '''
                            cd mle-lab4
                            export PATH=$PATH:/usr/local/bin && /usr/local/bin/docker-compose up -d
                        '''
                    }
                }
            }
        }

        stage('Checkout container logs') {
            steps {
                dir("mle-lab4") {
                    sh '''
                        ls
                        export PATH=$PATH:/usr/local/bin
                        containerId=$(/usr/local/bin/docker ps -qf "name=mle-lab4-penguin-app")
                        echo $containerId
                        if [ ! -z "$containerId" ]; then
                            docker logs $containerId
                        else
                            echo "Container not found"
                        fi
                    '''
                }
            }
        }

        stage('Stop and Remove Docker Container') {
            steps {
                script {
                    sh '''
                        containerId=$(/usr/local/bin/docker ps -qf "name=mle-lab4-penguin-app")
                        if [ ! -z "$containerId" ]; then
                            /usr/local/bin/docker stop $containerId
                            /usr/local/bin/docker rm $containerId
                            echo "Container stopped and removed"
                        else
                            echo "No container running with the name mle-lab4-penguin-app"
                        fi
                    '''
                }
            }
        }

        stage('Push') {
            steps {
                sh '''
                    export PATH=$PATH:/usr/local/bin && /usr/local/bin/docker push sesh31/mle-lab4-penguin-app:latest
                '''
            }
        }

        stage('Trigger CD Pipeline') {
            steps {
                script {
                    build job: 'CD', propagate: true
                }
            }
        }
    }

    post {
        always {
            script {
                sh '''
                    cd mle-lab4
                    export PATH=$PATH:/usr/local/bin && /usr/local/bin/docker logout
                '''
            }
        }
    }
}
